<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AsyncKeyedLock" Version="7.1.7" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Refit" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OrderService.Application\OrderService.Application.csproj" />
      <ProjectReference Include="..\OrderService.Domain\OrderService.Domain.csproj" />
    </ItemGroup>

</Project>
