<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DistributedLock.Redis" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
      <PackageReference Include="Refit" Version="9.0.2" />
      <PackageReference Include="Refit.HttpClientFactory" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\OrderService.Domain\OrderService.Domain.csproj" />
    </ItemGroup>

</Project>
