color = ''
project-name = 'default'

[default]
account_id = 'acct_1ShsE90ZIE9VHzzn'
device_name = 'MacBook-Air-Rodion.local'
display_name = 'New business sandbox'
test_mode_api_key = 'sk_test_51ShsE90ZIE9VHzznvMlK7lcQtyhKIuMjn8gHXlVji9J8El9V4r97nV0xCPCPGxq316sYzKiKuPUoa8zm9tELtxfS00tvpF5cEm'
test_mode_pub_key = 'pk_test_51ShsE90ZIE9VHzzn6RrvwgWHktDfZvQfN9C4aBnwHGn3tuyaEWujL9EAsXPLc5S12NbQQjZwa565uu5W7izwKLxj00l0TMWpy4'
