// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ChatClient.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116085938_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding1024")
                        .HasColumnType("vector(1024)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Chunks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3d5e7f9-1b2c-4d6e-8f0a-9b3c5d7e9f01"),
                            ProductId = new Guid("a3d5e7f9-1b2c-4d6e-8f0a-9b3c5d7e9f01")
                        },
                        new
                        {
                            Id = new Guid("b4e6f8a0-2c3d-5e7f-9a1b-4c6d8e0f2a3b"),
                            ProductId = new Guid("b4e6f8a0-2c3d-5e7f-9a1b-4c6d8e0f2a3b")
                        },
                        new
                        {
                            Id = new Guid("c5f7a9b1-3d4e-6f8a-0b2c-5d7f9a1c3d4e"),
                            ProductId = new Guid("c5f7a9b1-3d4e-6f8a-0b2c-5d7f9a1c3d4e")
                        },
                        new
                        {
                            Id = new Guid("d6f8b0c2-4e5f-7a9b-1c3d-6e8f0b2d4e5f"),
                            ProductId = new Guid("d6f8b0c2-4e5f-7a9b-1c3d-6e8f0b2d4e5f")
                        },
                        new
                        {
                            Id = new Guid("e7f9c1d3-5f6a-8b0c-2d4e-7f9a1c3e5f6a"),
                            ProductId = new Guid("e7f9c1d3-5f6a-8b0c-2d4e-7f9a1c3e5f6a")
                        },
                        new
                        {
                            Id = new Guid("f8a0d2e4-6a7b-9c1d-3e5f-8a0b2d4f6a7b"),
                            ProductId = new Guid("f8a0d2e4-6a7b-9c1d-3e5f-8a0b2d4f6a7b")
                        },
                        new
                        {
                            Id = new Guid("09b1e3f5-7b8c-0d2e-4f6a-9b1c3e5f7b8c"),
                            ProductId = new Guid("09b1e3f5-7b8c-0d2e-4f6a-9b1c3e5f7b8c")
                        },
                        new
                        {
                            Id = new Guid("1a2c4e6f-8c9d-1e3f-5a7b-8c2d4e6f8c9d"),
                            ProductId = new Guid("1a2c4e6f-8c9d-1e3f-5a7b-8c2d4e6f8c9d")
                        },
                        new
                        {
                            Id = new Guid("2b3d5f7a-9d0e-2f4a-6b8c-9d3e5f7a9d0e"),
                            ProductId = new Guid("2b3d5f7a-9d0e-2f4a-6b8c-9d3e5f7a9d0e")
                        },
                        new
                        {
                            Id = new Guid("3c4e6a8b-0e1f-3a5b-7c9d-0e4f6a8b0e1f"),
                            ProductId = new Guid("3c4e6a8b-0e1f-3a5b-7c9d-0e4f6a8b0e1f")
                        });
                });

            modelBuilder.Entity("Chunk", b =>
                {
                    b.OwnsOne("ProductShortInfo", "ProductInfo", b1 =>
                        {
                            b1.Property<Guid>("ChunkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductInfoDescription");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductInfoId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProductInfoName");

                            b1.HasKey("ChunkId");

                            b1.ToTable("Chunks");

                            b1.WithOwner()
                                .HasForeignKey("ChunkId");

                            b1.HasData(
                                new
                                {
                                    ChunkId = new Guid("a3d5e7f9-1b2c-4d6e-8f0a-9b3c5d7e9f01"),
                                    Description = "Classic Italian pizza with tomato sauce, fresh mozzarella, basil leaves, and olive oil. Thin crispy crust and authentic flavor.",
                                    Id = new Guid("a3d5e7f9-1b2c-4d6e-8f0a-9b3c5d7e9f01"),
                                    Name = "Margherita Pizza"
                                },
                                new
                                {
                                    ChunkId = new Guid("b4e6f8a0-2c3d-5e7f-9a1b-4c6d8e0f2a3b"),
                                    Description = "Spicy pizza with pepperoni slices, double mozzarella cheese, tomato sauce, and Italian herbs.",
                                    Id = new Guid("b4e6f8a0-2c3d-5e7f-9a1b-4c6d8e0f2a3b"),
                                    Name = "Pepperoni Pizza"
                                },
                                new
                                {
                                    ChunkId = new Guid("c5f7a9b1-3d4e-6f8a-0b2c-5d7f9a1c3d4e"),
                                    Description = "Pizza with grilled chicken, BBQ sauce, red onions, cilantro, and mozzarella cheese.",
                                    Id = new Guid("c5f7a9b1-3d4e-6f8a-0b2c-5d7f9a1c3d4e"),
                                    Name = "BBQ Chicken Pizza"
                                },
                                new
                                {
                                    ChunkId = new Guid("d6f8b0c2-4e5f-7a9b-1c3d-6e8f0b2d4e5f"),
                                    Description = "Juicy beef patty with cheddar cheese, lettuce, tomato, onion, pickles, and special sauce.",
                                    Id = new Guid("d6f8b0c2-4e5f-7a9b-1c3d-6e8f0b2d4e5f"),
                                    Name = "Classic Cheeseburger"
                                },
                                new
                                {
                                    ChunkId = new Guid("e7f9c1d3-5f6a-8b0c-2d4e-7f9a1c3e5f6a"),
                                    Description = "Beef burger with crispy bacon, American cheese, caramelized onions, and smoky BBQ sauce.",
                                    Id = new Guid("e7f9c1d3-5f6a-8b0c-2d4e-7f9a1c3e5f6a"),
                                    Name = "Bacon Burger"
                                },
                                new
                                {
                                    ChunkId = new Guid("f8a0d2e4-6a7b-9c1d-3e5f-8a0b2d4f6a7b"),
                                    Description = "Crispy chicken fillet with spicy mayo, lettuce, tomato, and pickles.",
                                    Id = new Guid("f8a0d2e4-6a7b-9c1d-3e5f-8a0b2d4f6a7b"),
                                    Name = "Spicy Chicken Burger"
                                },
                                new
                                {
                                    ChunkId = new Guid("09b1e3f5-7b8c-0d2e-4f6a-9b1c3e5f7b8c"),
                                    Description = "Crispy chicken tenders with fries, coleslaw, and dipping sauce.",
                                    Id = new Guid("09b1e3f5-7b8c-0d2e-4f6a-9b1c3e5f7b8c"),
                                    Name = "Chicken Basket"
                                },
                                new
                                {
                                    ChunkId = new Guid("1a2c4e6f-8c9d-1e3f-5a7b-8c2d4e6f8c9d"),
                                    Description = "Spicy chicken wings with celery, carrots, and blue cheese dressing.",
                                    Id = new Guid("1a2c4e6f-8c9d-1e3f-5a7b-8c2d4e6f8c9d"),
                                    Name = "Spicy Chicken Basket"
                                },
                                new
                                {
                                    ChunkId = new Guid("2b3d5f7a-9d0e-2f4a-6b8c-9d3e5f7a9d0e"),
                                    Description = "Pizza with ham, pineapple, mozzarella, and tomato sauce.",
                                    Id = new Guid("2b3d5f7a-9d0e-2f4a-6b8c-9d3e5f7a9d0e"),
                                    Name = "Hawaiian Pizza"
                                },
                                new
                                {
                                    ChunkId = new Guid("3c4e6a8b-0e1f-3a5b-7c9d-0e4f6a8b0e1f"),
                                    Description = "Plant-based patty with avocado, lettuce, tomato, and vegan mayo.",
                                    Id = new Guid("3c4e6a8b-0e1f-3a5b-7c9d-0e4f6a8b0e1f"),
                                    Name = "Veggie Burger"
                                });
                        });

                    b.Navigation("ProductInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
