// <auto-generated />
using System;
using ChatService.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatService.API.Migrations;

[DbContext(typeof(ChatDbContext))]
partial class ChatDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ChatService.API.Models.ChatMessage", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("OrderId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<string>("SenderName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<DateTime>("SentAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Text")
                .IsRequired()
                .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("OrderId");

            b.ToTable("Messages");
        });
#pragma warning restore 612, 618
    }
}
